### ISSUE TITLE
怎么清除该脚本运行的东西

### ISSUE THREAD

**Issue by zrwkkd** [dqzboy/ShellProject#5]
rt

**Comment by dqzboy** [comment]
卸载安装的组件的话 需要通过`rpm -qa`过滤安装的包，然后在`rpm -e` 进行卸载；后面我加个一键卸载

**Comment by zrwkkd** [comment]
> 卸载安装的组件的话 需要通过`rpm -qa`过滤安装的包，然后在`rpm -e` 进行卸载；后面我加个一键卸载

好的
