### ISSUE TITLE
遇到错误 azure新机器直接安装的ub20.04

### ISSUE THREAD

**Issue by sizxiwu** [dqzboy/ShellProject#6]
![image](https://user-images.githubusercontent.com/121373708/232266607-c6cc1ab9-ec1e-4ea7-93cb-54356b44e5f2.png)
![image](https://user-images.githubusercontent.com/121373708/232266616-258d5c0f-ca16-42f7-b7af-121a9dc743de.png)

**Comment by dqzboy** [comment]
机器啥规格呀？内存不足

**Comment by sizxiwu** [comment]
多半是，1g内存 1g交换

dqzboy ***@***.***> 于 2023年4月16日周日 下午12:40写道：
