### ISSUE TITLE
请教下 nextweb 同web有什么区别

### ISSUE THREAD

**Issue by linyu0219** [dqzboy/ShellProject#7]
另外 https://hostloc.com/forum.php?mod=viewthread&tid=1160522&extra=&highlight=chatgpt&page=1 hostloc上有一个扫chatgpt接口的如何防止被扫

**Comment by dqzboy** [comment]
这是nex-web作者的回复
![image](https://user-images.githubusercontent.com/42825450/232696517-019c5c63-c7a1-4900-8e77-8e97916df458.png)
- 防止被扫
  - 通过nginx配置，防止机器人扫描
  - 修改标题，不要带chatGPT相关信息

**Comment by zenith779** [comment]
nextweb不能使用access token吧
@dqzboy

**Comment by dqzboy** [comment]
> 

没有，后期也不会增加，这是作者的回复
![image](https://user-images.githubusercontent.com/42825450/232697647-3eb3d90c-d7ab-4f1a-8fe0-22836b05b37b.png)
