### ISSUE TITLE
反馈一个问题 cp: 无法创建目录"/usr/share/nginx/html": 没有那个文件或目录

### ISSUE THREAD

**Issue by Z-MoonDream** [dqzboy/ShellProject#8]
纯净环境，什么都没有，执行脚本，会出现这个问题

**Comment by dqzboy** [comment]
这个是nginx没有安装成功，我加个判断逻辑

**Comment by Kalpeny** [comment]
问个小白问题，安装成功后要怎么访问呢？端口是多少？

**Comment by dqzboy** [comment]
端口80  直接你的服务器公网IP访问

**Comment by Kalpeny** [comment]
> 
直接访问或者80端口不行，出现下面提示
Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

**Comment by dqzboy** [comment]
之前服务器有Nginx吗？新环境？

**Comment by Kalpeny** [comment]
> 之前服务器有Nginx吗？新环境？

之前装过docker版nginx proxy manager，已经卸载了

**Comment by dqzboy** [comment]
1、ps -ef|grep nginx看下现在启动的Nginx进程
2、看下/usr/share/nginx/html 目录下有没有文件

**Comment by Kalpeny** [comment]
> 1、ps -ef|grep nginx看下现在启动的Nginx进程 2、看下/usr/share/nginx/html 目录下有没有文件

ok

**Comment by Kalpeny** [comment]
> 1、ps -ef|grep nginx看下现在启动的Nginx进程 2、看下/usr/share/nginx/html 目录下有没有文件

可以通过ip访问了，我域名解析到ip上，直接访问域名还是Welcome to nginx!

**Comment by dqzboy** [comment]
域名访问你得修改nginx配置，配置成你的域名才行
