### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by lonny1987** [dqzboy/ShellProject#9]
### 前置确认

- [X] 我确认我的网络可以访问openai，使用的是最新脚本，并且服务器规格 > 1C1G

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Ubuntu

### 复现步骤 🕹

<img width="894" alt="image" src="https://user-images.githubusercontent.com/129271373/235210646-d12f68a7-6470-4370-b27e-68a603e45214.png">

### 终端日志 📒

```log
<此处粘贴终端日志>
```
<img width="894" alt="image" src="https://user-images.githubusercontent.com/129271373/235210659-f8f0b908-1b38-42f7-b552-53771200f2b3.png">

**Comment by dqzboy** [comment]
启动日志贴一下

**Comment by lonny1987** [comment]
Error: Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable
Apr 29 01:08:41 cvm-3k6cig825i223 pnpm[29477]:     at options (/usr/share/nginx/html/service/src/chatgpt/index.ts:33:9)
Apr 29 01:08:41 cvm-3k6cig825i223 pnpm[29477]:     at Object.<anonymous> (/usr/share/nginx/html/service/src/chatgpt/index.ts:212:10)
Apr 29 01:08:41 cvm-3k6cig825i223 pnpm[29477]:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
Apr 29 01:08:41 cvm-3k6cig825i223 pnpm[29477]:     at Object.F (/usr/share/nginx/html/service/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
Apr 29 01:08:41 cvm-3k6cig825i223 pnpm[29477]:     at Module.load (node:internal/modules/cjs/loader:1117:32)
Apr 29 01:08:41 cvm-3k6cig825i223 pnpm[29477]:     at Module._load (node:internal/modules/cjs/loader:958:12)
Apr 29 01:08:41 cvm-3k6cig825i223 pnpm[29477]:     at Module.require (node:internal/modules/cjs/loader:1141:19)
Apr 29 01:08:41 cvm-3k6cig825i223 pnpm[29477]:     at require (node:internal/modules/cjs/helpers:110:18)
Apr 29 01:08:41 cvm-3k6cig825i223 pnpm[29477]:     at <anonymous> (/usr/share/nginx/html/service/src/index.ts:4:60)
Apr 29 01:08:41 cvm-3k6cig825i223 pnpm[29477]:     at Object.<anonymous> (/usr/share/nginx/html/service/src/index.ts:89:80)
Apr 29 01:08:41 cvm-3k6cig825i223 pnpm[29477]: Node.js v18.16.0
Apr 29 01:08:41 cvm-3k6cig825i223 pnpm[29449]:  ELIFECYCLE  Command failed with exit code 1.

**Comment by dqzboy** [comment]
Error: Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN

配置一下，文档有写

**Comment by lonny1987** [comment]
好的，感谢你了，我是不是理解错了，我以为你的代码就一键安装自动 运行，刚手动去根目录下用pnpm start竟然成功启动了，感谢大神的代码 ，超级无敌

**Comment by dqzboy** [comment]
env配置需要根据自己的情况进行修改

**Comment by lonny1987** [comment]
好像也是不行，我不会部署哈哈！

**Comment by lonny1987** [comment]
oot@cvm-3k6cig825i223:~/chatgpt-web/service# pnpm start

> chatgpt-web-service@1.0.0 start /root/chatgpt-web/service
> esno ./src/index.ts

Server is running on port 3002

**Comment by dqzboy** [comment]
下载仓库下面的env.example示例文件，并与脚本文件存放在同级目录下，执行脚本前记得修改文件里的相关参数，例如API KEY等信息

然后再次运行脚本即可正常启动

**Comment by lonny1987** [comment]
> 下载仓库下面的env.example示例文件，并与脚本文件存放在同级目录下，执行脚本前记得修改文件里的相关参数，例如API KEY等信息
> 
> 然后再次运行脚本即可正常启动

感谢大神指导 ，已经 可以正常运行了，大神有没有交流群或者 VX加下一
